config/routes.rb
Realestate::Application.routes.draw do

  match "webuy" => "sellers#new"
  match "WeBuy" => "sellers#new"
  match "WEBUY" => "sellers#new"
  match "Webuy" => "sellers#new"
  match "WEBuy" => "sellers#new"
  match "thankyou_webuy" => "homes#thankyou_webuy"

  resources :blog_comments do
    resources :blog_comments
  end

  resources :blogs do
    member do
      post "comment", "reply"
    end
    resources :blog_comments
  end
  

  resources :sellers

  namespace :member do
    resources :contacts
    root :to => "contacts#index"
  end
  
  namespace :admin do
    resources :contacts
    resources :users  #TODO: this should be in admin name space
  end

  
  

  resources :contacts
  
  resources :homes do
    collection do
      get 'sell', 'buy', 'lend', 'borrow', 'thankyou_webuy'
    end
  end

  devise_for :users 
  
  get "homes/thankyou_webuy"

  resources :users, :only => :show

  

  root :to => "sellers#new" #root :to => "homes#index"
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :blog_comments
  
  scope :sorted, :order => "created_at desc"
  

end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  belongs_to :parent , :class_name => "BlogComment", :foreign_key => "comment_id"
  has_many :replies, :class_name => "BlogComment", :foreign_key => "comment_id"
  
  validates_presence_of :name, :email, :comment
  
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
end

app/models/chronology.rb
class Chronology < ActiveRecord::Base
  belongs_to :prospective_property
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  
    
  has_many :contact_emails
  has_many :contact_addresses
  has_many :contact_dates
  has_many :contact_notes
  has_many :contact_phones
  has_many :contact_websites
  has_many :work_infos
  
  
  accepts_nested_attributes_for :contact_emails
  accepts_nested_attributes_for :contact_addresses
  accepts_nested_attributes_for :contact_dates
  accepts_nested_attributes_for :contact_notes
  accepts_nested_attributes_for :contact_phones
  accepts_nested_attributes_for :contact_websites
  accepts_nested_attributes_for :work_infos
  
  
end

app/models/contact_date.rb
class ContactDate < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/models/contact_email.rb
class ContactEmail < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
  
  validates_presence_of :email
end

app/models/contact_note.rb
class ContactNote < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/models/contact_phone.rb
class ContactPhone < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/models/label.rb
class Label < ActiveRecord::Base
end

app/models/lender.rb
class Lender < ActiveRecord::Base
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :rememberable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :lockable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  
  validates_presence_of :name, :email, :username
  validates_uniqueness_of :username, :email, :case_sensitive => false
  
  has_many :contacts
  has_many :blogs
  has_many :blog_comments, :through => :blogs
  
  has_many :prospective_properties
  
  
  accepts_nested_attributes_for :prospective_properties
  
  attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me
end

app/models/work_info.rb
class WorkInfo < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sellers }
    end
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    #@seller = Seller.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/new
  # GET /sellers/new.json
  def new
    @seller = Seller.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/1/edit
  def edit
    #@seller = Seller.find(params[:id])
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(params[:seller])

    respond_to do |format|
      if @seller.save
        SellerMailer.submission_confirmation(@seller).deliver
        SellerMailer.submission_notification(@seller).deliver
        format.html { redirect_to thankyou_webuy_homes_path, notice: 'Your request was successfully sent.' }
        format.json { render json: @seller, status: :created, location: @seller }
      else
        SellerMailer.submission_attempt_notification(@seller).deliver
        format.html { render action: "new" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sellers/1
  # PUT /sellers/1.json
  def update
    #@seller = Seller.find(params[:id])

    respond_to do |format|
      if @seller.update_attributes(params[:seller])
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    #@seller = Seller.find(params[:id])
    #@seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  #comments should be a blog_comment collection object
  def show_blog_comments(comments)
    "TODO: Finish this helper in BlogsHelper"
  end

  #recursive function to print all the comments
  def print_comment_replies(comment, level = 0)
    str = "<div class='spacer' style='margin:2px 0 2px #{level*30}px;'>"
    str += render :partial => 'reply', :locals => {:comment => comment}
    str += render :partial => 'reply_form', :locals => {:comment => comment}
    str += "</div>"
    
    comment.replies.each do |reply|
      str += print_comment_replies(reply, level + 1 )
    end
    str
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/sellers/_form.html.erb
<div class="row1">
  Fast Response Form
</div>
<%= form_for(@seller) do |f| %>

  <% if @seller.errors.any? %>
    <div class="row2">
      <div id="error_explanation">
        <h2><%= pluralize(@seller.errors.count, "error") %> are preventing your submission.  Please fill out the highlighted fields so that can contact you and start our research:</h2>

        <ul>
        <% @seller.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="row2">
    <div class="row">
      <div class="field">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name,:size => 10 %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name,:size => 10  %>
      </div>
    </div>
    <div class="row">
      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email,:size => 10  %>
      </div>
      <div class="field">
        <%= f.label :cell_phone %><br />
        <%= f.text_field :cell_phone,:size => 10  %>
      </div>
    </div>
    <div class="row_wide">
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address %>
      </div>
    </div>
    <div class="row_small">
      <div class="field">
        <%= f.label :city %><br />
        <%= f.text_field :city,:size => 10  %>
      </div>
      <div class="field">
        <%= f.label :state %><br />
        <%= f.text_field :state,:size => 3 %>
      </div>
      <div class="field">
        <%= f.label :zipcode %><br />
        <%= f.text_field :zipcode,:size => 5 %>
      </div>
    </div>
    <div class="row">
      <div class="field">
        <%= f.label :bedrooms %><br />
        <%= f.text_field :bedrooms,:size => 4 %>
      </div>
      <div class="field">
        <%= f.label :baths %><br />
        <%= f.text_field :baths,:size => 4 %>
      </div>
    </div>
    <div class="row">
      <div class="field">
        <%= f.label :current_market_value %><br />
        <%= f.text_field :current_market_value,:size => 14  %>
      </div>
      <div class="field">
        <%= f.label :liens_against_property %><br />
        <%= f.text_field :liens_against_property,:size => 14  %>
      </div>
    </div>

    <div class="row">
      <div class="field">
        <%= f.label :when_to_sell %><br />
        <%= f.text_field :when_to_sell,:size => 10  %>
      </div>
      <div class="field">
        <%= f.label :current_on_payments %><br />
        <%= f.text_field :current_on_payments,:size => 10  %>
      </div>
    </div>
    <div class="row">
      <div class="field">
        <%= f.label :repairs_needed %><br />
        <%= f.text_field :repairs_needed,:size => 10  %>
      </div>
    </div>
    <div class="row">
      <div class="field">
        <%= f.label :comment, "Any important details:" %><br />
        <%= f.text_area :comment,:size => "25x3" %>
      </div>
    </div>
    <div class="row">
      <div class="field">
        <%= f.label :referral, "Referred By:" %><br />
        <%= f.text_field :referral,:size => 10  %>
      </div>
      <div class="field">
        <%= f.label :on_mls, "Is House on MLS?" %>
        <%= f.check_box :on_mls %>
      </div>
    </div>
  </div>
  <div class="row3">
    <div class="actions">
      <%= f.submit "Make me an offer" %>
    </div>
  </div>
<% end %>

app/views/admin/sellers/_sell_reasons_foreclosure.html.erb
<h1>Need help with your Foreclosure or preforeclosure?</h1>

<p>Foreclosure and preforeclosure is a terrible experience that many americans are going through because of a poor economy and preditory lending practices.  Many banks don't even treat you like a person and when you are trying to work it out you can spend days on hold, being bounced around and finally flat out ignored and required to left voice messages that will never be heard.</p>

<p>We may be able to help you avoid bankruptcy and save as much of your credit as posible. <em>Bankruptcy will often not solve your problem and make your life more difficult and do incredible damage to your credit.</em>  Watch out for attornies because after all, they make money by spending hours working over your problems and you can often end up with a bigger problem then when you started.  When we talk, I'll recommend a few good ones.  Even if you do go through the foreclosure process there are tax concequenses that you want to be prepared for and I know attornies that might be able to help you avoid those.  That being said, you should know if bankruptcy is really the solution for you.</p>

<p><em>We might be able to keep you in your home!</em>  You may or may not be interested in staying in your home. We can come up with a solution that helps meet your goals</p>

app/views/admin/sellers/_sell_reasons_land_lord.html.erb
<h3>How Many of These “Rental House Nightmares” Have Happened to You?</h3>

<ul>
<li>Late Rent Checks</li>
<li>Rent Checks That Bounce</li>
<li>Property Needs Constant Maintenance</li>
<li>Tenants Tear Up Your Property!</li>
<li>Ineffective Property Management Companies and Ridiculously High Repair Bills</li>
</ul>

<p>Maybe you’re tired of tenant hassles and have already decided to sell… or, 
maybe you’re still looking for that perfect tenant. Either way, this letter 
will give you some priceless hints … plus save you thousands of 
dollars and massive amounts of frustration!</p>


<p>My name is Phil Cutting and our company leases and purchases a lot of rent
 houses in the Columbus area every year from fed-up landlords. If you’re tired
  of tenants and management hassles, consider this great service!</p>

<p>Sooner or later, most landlords get fed up with the hassle of repairs,
 maintenance, and tenant problems. Others who have hired property management
  companies are tired of the aggravation and inflated repair bills.</p>

<p>I’ve talked to 100’s of landlords, and it generally comes down to one
 or more of the reasons discussed in this letter.</p>

<p>First is that you’ve come to hate dealing with tenants. This is particularly
 true if you’re an “accidental landlord”. Maybe you moved to a bigger house, 
 another city, or inherited a property and decided to rent it out (or maybe 
 couldn’t sell it).</p>

<p>You cringe every time your tenants call. It’s either some silly complaint
 or more maintenance! Can’t they fix anything themselves? Or even worse –  
 they don’t call, and the leak under the sink rots out the cabinet and the wall 
 behind it.</p>

<p>Many times the tenants move out you’re left with a lot of deferred maintenance
 that would have been cheap to fix if it was done immediately, but now is a major
  expensive nightmare.</p>

<p>Then there’s the rent. If you’re like most landlords, you could publish a 
book with all the excuses you’ve heard!</p>

<p>Do you live hundreds of miles away…</p>

<p>Do you live hundreds of miles away and can’t afford to fly back and forth 
every time when your tenants move out? Do you have a good handle on repair 
bills? Aren’t they too high?</p>

<p>Expensive, but ineffective Property Management companies…</p>

<p>Sure, you can hire a management company to handle all this – at a pretty 
steep price.  You pay one months rent for commission every time a tenant moves 
out.  Then, you pay 10% every month for management fees.  And if that doesn’t 
tear into your profit enough, repair bills are marked up 20%.</p>

<p>If you’ve decided to sell your rental, it’ll probably need a major cosmetic 
fix up. In reality you’ll be competing with homeowners selling their personal
 residences, so you have to spruce it up to their level. And that is no issue 
 if you are in the fixer-upper business. But if you have to hire contractors 
 to take care of all the deferred maintenance and the fix up, you are looking 
 at thousands of dollars and more headaches.</p>

<p>If you have to do only minor repairs, you can probably do it while the 
tenant is still in there.</p>

<p>Maybe you think you can sell your rental house through a realtor with a 
tenant in it. Not very likely! The realtor has to schedule showings at the 
tenants’ convenience (and it’s never convenient), and the tenants have no 
interest in cleaning the house so it shows well. Realtors hate this kind of 
listing and many won’t be motivated to even show them.</p>

<p>How can you sell your rental without spending a lot of money on repairs 
and on commissions?</p>


<p>Very simple! Just pick up the phone and call us at (614) 358-1944 or even 
easier, fill out the form to the right. I can do a drive-by inspection of the 
house and make you an offer without alerting your tenants.</p>

<p>If you're interested in stopping tenant hassles, and selling your house in the
 easiest way possible, fill out the form to the right or please call my office at 
 (614) 358-1944 as soon as  possible, even easier, fill out the form to the left.. 
 I look forward to hearing from you.</p>
 
<p><em>I forgot to mention this … you will save thousands of dollars by not making payments on a vacant house until your buyer qualifies for the loan! This is a fast way to cash out on your rental house!</em></p>

app/views/admin/sellers/_sell_reasons_need_fast_cash.html.erb
<h2>We specialize in helping people who need to sell their house quickly for a variety of circumstances. Some of the reasons we see most often are:</h2>
<ol>
  <li>Behind on payments or facing foreclosure.</li>
  <li>Recently separated or divorced.</li>
  <li>Transferring jobs or relocating.</li>
  <li>Bought a new property and need to sell the old one first.</li>
  <li>Need to settle an estate.</li>
  <li>Real Estate agent could not sell the house.</li>
  <li>Tired of the headaches of being a landlord.</li>
  <li>House is vacant and costs are piling up.</li>
  <li>House is in need of repairs.</li>
  <li>You just need cash for a project or to pay off debt.</li>
</ul>

<h2>Why choose Lion MGT LLC?</h2>
<ul>
  <li>Guaranteed property sale at competitive, agreed upon price.</li>
  <li>Fast and hassle- free, you will have a offer in 48 hours or less.</li>
  <li>We use private funding or cash so we can close in 7-14 days or less.</li>
  <li>We handle all the paper work and make all the arrangements.</li>
  <li>You get a simple, no hassle closing, with NO cost to you.</li>
  <li>Property purchased 'as-is' with no further expense, clean up,repairs
  or improvements.</li>
  <li>No 6% realtor fee. There are never any fees or commissions.<br/>
  We don't want to list your property; we want to buy it for cash!</li>
  <li>Strictly confidential.</li>
</ul>

app/views/admin/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/admin/sellers/index.html.erb
<h1>Listing sellers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Cell phone</th>
    <th>Home phone</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Bedrooms</th>
    <th>Baths</th>
    <th>Current market value</th>
    <th>Liens against property</th>
    <th>Referral</th>
    <th>When to sell</th>
    <th>Current on payments</th>
    <th>Repairs needed</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sellers.each do |seller| %>
  <tr>
    <td><%= seller.name %></td>
    <td><%= seller.email %></td>
    <td><%= seller.cell_phone %></td>
    <td><%= seller.home_phone %></td>
    <td><%= seller.address %></td>
    <td><%= seller.city %></td>
    <td><%= seller.state %></td>
    <td><%= seller.zipcode %></td>
    <td><%= seller.bedrooms %></td>
    <td><%= seller.baths %></td>
    <td><%= seller.current_market_value %></td>
    <td><%= seller.liens_against_property %></td>
    <td><%= seller.referral %></td>
    <td><%= seller.when_to_sell %></td>
    <td><%= seller.current_on_payments %></td>
    <td><%= seller.repairs_needed %></td>
    <td><%= seller.comment %></td>
    <td><%= link_to 'Show', seller %></td>
    <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
    <td><%= link_to 'Destroy', seller, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seller', new_seller_path %>

app/views/admin/sellers/new.html.erb
<h1>We will buy your property Quickly!</h1>

<% if session[:name].present? %> 
  Hi <%= session[:name].to_s %>,<br/>
<% end %>

<div class="content seller_content">
  <div class="section">
    <div class="column">
      <div class="article options">
        <%= button_to "Need to Sell Quick", "#", class: "options", :id => "button_sell_quick" %>
        <%= button_to "Hate Landlording", "#", class: "options", :id => "button_hates_landlording" %>
        <%= button_to "Foreclosure", "#", class: "options", :id => "button_foreclosure" %>  
      </div>
      <div class="youtube">
        <%= video_tag("We buy video for lion mgt Take 1.mp4", :autoplay => true, :loop => false, :controls => true, :autobuffer => true) %>
      </div>
      <div class="article" id="seller_hates_being_land_lord">
        <%= render :partial => "sell_reasons_land_lord" %>
      </div>
      <div class="article" id="seller_sell_quick">
        <%= render :partial => "sell_reasons_need_fast_cash" %>
      </div>
      <div class="article" id="seller_foreclosure">
        <%= render :partial => "sell_reasons_foreclosure" %>
      </div> 
    </div>
    <div class="form">  
      <%= render 'form' %>
    </div>
  </div>
</div>


  

  

app/views/admin/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @seller.first_name %>
</p>

<p>
  <b>Email:</b>
  <%= @seller.email %>
</p>

<p>
  <b>Cell phone:</b>
  <%= @seller.cell_phone %>
</p>

<p>
  <b>Home phone:</b>
  <%= @seller.home_phone %>
</p>

<p>
  <b>Address:</b>
  <%= @seller.address %>
</p>

<p>
  <b>City:</b>
  <%= @seller.city %>
</p>

<p>
  <b>State:</b>
  <%= @seller.state %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @seller.zipcode %>
</p>

<p>
  <b>Bedrooms:</b>
  <%= @seller.bedrooms %>
</p>

<p>
  <b>Baths:</b>
  <%= @seller.baths %>
</p>

<p>
  <b>Current market value:</b>
  <%= @seller.current_market_value %>
</p>

<p>
  <b>Liens against property:</b>
  <%= @seller.liens_against_property %>
</p>

<p>
  <b>Referral:</b>
  <%= @seller.referral %>
</p>

<p>
  <b>When to sell:</b>
  <%= @seller.when_to_sell %>
</p>

<p>
  <b>Current on payments:</b>
  <%= @seller.current_on_payments %>
</p>

<p>
  <b>Repairs needed:</b>
  <%= @seller.repairs_needed %>
</p>

<p>
  <b>Comment:</b>
  <%= @seller.comment %>
</p>


<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/new.html.erb
<h1>We will buy your property Quickly!</h1>

<% if session[:name].present? %> 
  Hi <%= session[:name].to_s %>,<br/>
<% end %>

<div class="content seller_content">
  <div class="section">
    <div class="column">
      <div class="article options">
        <%= button_to "Need to Sell Quick", "#", class: "options", :id => "button_sell_quick" %>
        <%= button_to "Hate Landlording", "#", class: "options", :id => "button_hates_landlording" %>
        <%= button_to "Foreclosure", "#", class: "options", :id => "button_foreclosure" %>  
      </div>
      <div class="youtube">
        <%= video_tag ["/videos/We buy video for lion mgt Take 1.mp4","/videos/we_buy_video.ogv", "/videos/we_buy_video.webm"], :autoplay => false, :loop => false, :controls => true, :autobuffer => true, :width => 450 %>
      </div>
      <div class="article" id="seller_hates_being_land_lord">
        <%= render :partial => "sell_reasons_land_lord" %>
      </div>
      <div class="article" id="seller_sell_quick">
        <%= render :partial => "sell_reasons_need_fast_cash" %>
      </div>
      <div class="article" id="seller_foreclosure">
        <%= render :partial => "sell_reasons_foreclosure" %>
      </div> 
    </div>
    <div class="form">  
      <%= render 'form' %>
    </div>
  </div>
</div>


  

  