config/routes.rb
Realestate::Application.routes.draw do

  match "webuy" => "sellers#new"
  match "WeBuy" => "sellers#new"
  match "WEBUY" => "sellers#new"
  match "Webuy" => "sellers#new"
  match "WEBuy" => "sellers#new"
  match "thankyou_webuy" => "homes#thankyou_webuy"

  resources :blog_comments do
    resources :blog_comments
  end

  resources :blogs do
    member do
      post "comment", "reply"
    end
    resources :blog_comments
  end
  

  resources :sellers

  namespace :member do
    resources :contacts
    root :to => "contacts#index"
  end
  
  namespace :admin do
    resources :contacts
    resources :users  #TODO: this should be in admin name space
  end

  
  

  resources :contacts
  
  resources :homes do
    collection do
      get 'sell', 'buy', 'lend', 'borrow', 'thankyou_webuy'
    end
  end

  devise_for :users 
  
  get "homes/thankyou_webuy"

  resources :users, :only => :show

  

  root :to => "sellers#new" #root :to => "homes#index"
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :blog_comments
  
  scope :sorted, :order => "created_at desc"
  

end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  belongs_to :parent , :class_name => "BlogComment", :foreign_key => "comment_id"
  has_many :replies, :class_name => "BlogComment", :foreign_key => "comment_id"
  
  validates_presence_of :name, :email, :comment
  
end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
end

app/models/chronology.rb
class Chronology < ActiveRecord::Base
  belongs_to :prospective_property
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  
    
  has_many :contact_emails
  has_many :contact_addresses
  has_many :contact_dates
  has_many :contact_notes
  has_many :contact_phones
  has_many :contact_websites
  has_many :work_infos
  
  
  accepts_nested_attributes_for :contact_emails
  accepts_nested_attributes_for :contact_addresses
  accepts_nested_attributes_for :contact_dates
  accepts_nested_attributes_for :contact_notes
  accepts_nested_attributes_for :contact_phones
  accepts_nested_attributes_for :contact_websites
  accepts_nested_attributes_for :work_infos
  
  
end

app/models/contact_date.rb
class ContactDate < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/models/contact_email.rb
class ContactEmail < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
  
  validates_presence_of :email
end

app/models/contact_note.rb
class ContactNote < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/models/contact_phone.rb
class ContactPhone < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/models/label.rb
class Label < ActiveRecord::Base
end

app/models/lender.rb
class Lender < ActiveRecord::Base
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :rememberable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :lockable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  
  validates_presence_of :name, :email, :username
  validates_uniqueness_of :username, :email, :case_sensitive => false
  
  has_many :contacts
  has_many :blogs
  has_many :blog_comments, :through => :blogs
  
  has_many :prospective_properties
  
  
  accepts_nested_attributes_for :prospective_properties
  
  attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me
end

app/models/work_info.rb
class WorkInfo < ActiveRecord::Base
  belongs_to :user
  belongs_to :contact
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  # GET /blog_comments
  # GET /blog_comments.json
  def index
    @blog_comments = BlogComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_comments }
    end
  end

  # GET /blog_comments/1
  # GET /blog_comments/1.json
  def show
    @blog_comment = BlogComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_comment }
    end
  end

  # GET /blog_comments/new
  # GET /blog_comments/new.json
  def new
    @blog_comment = BlogComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_comment }
    end
  end

  # GET /blog_comments/1/edit
  def edit
    @blog_comment = BlogComment.find(params[:id])
  end

  # POST /blog_comments
  # POST /blog_comments.json
  def create
    @blog_comment = BlogComment.new(params[:blog_comment])

    respond_to do |format|
      if @blog_comment.save
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully created.' }
        format.json { render json: @blog_comment, status: :created, location: @blog_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_comments/1
  # PUT /blog_comments/1.json
  def update
    @blog_comment = BlogComment.find(params[:id])

    respond_to do |format|
      if @blog_comment.update_attributes(params[:blog_comment])
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_comments/1
  # DELETE /blog_comments/1.json
  def destroy
    @blog_comment = BlogComment.find(params[:id])
    @blog_comment.destroy

    respond_to do |format|
      format.html { redirect_to blog_comments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper

  #comments should be a blog_comment collection object
  def show_blog_comments(comments)
    "TODO: Finish this helper in BlogsHelper"
  end

  #recursive function to print all the comments
  def print_comment_replies(comment, level = 0)
    str = "<div class='spacer' style='margin:2px 0 2px #{level*30}px;'>"
    str += render :partial => 'reply', :locals => {:comment => comment}
    str += render :partial => 'reply_form', :locals => {:comment => comment}
    str += "</div>"
    
    comment.replies.each do |reply|
      str += print_comment_replies(reply, level + 1 )
    end
    str
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/label_helper.rb
module LabelHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_comments/_form.html.erb
<%= form_for(@blog_comment) do |f| %>
  <% if @blog_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>

      <ul>
      <% @blog_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :parent_comment %><br />
    <%= f.number_field :parent_comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_comments/edit.html.erb
<h1>Editing blog_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_comment %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/index.html.erb
<h1>Listing blog_comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Email</th>
    <th>Website</th>
    <th>Comment</th>
    <th>Parent comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog_comments.each do |blog_comment| %>
  <tr>
    <td><%= blog_comment.user %></td>
    <td><%= blog_comment.name %></td>
    <td><%= blog_comment.email %></td>
    <td><%= blog_comment.website %></td>
    <td><%= blog_comment.comment %></td>
    <td><%= blog_comment.parent_comment %></td>
    <td><%= link_to 'Show', blog_comment %></td>
    <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
    <td><%= link_to 'Destroy', blog_comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog comment', new_blog_comment_path %>

app/views/blog_comments/new.html.erb
<h1>New blog_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @blog_comment.user %>
</p>

<p>
  <b>Name:</b>
  <%= @blog_comment.name %>
</p>

<p>
  <b>Email:</b>
  <%= @blog_comment.email %>
</p>

<p>
  <b>Website:</b>
  <%= @blog_comment.website %>
</p>

<p>
  <b>Comment:</b>
  <%= @blog_comment.comment %>
</p>

<p>
  <b>Parent comment:</b>
  <%= @blog_comment.parent_comment %>
</p>


<%= link_to 'Edit', edit_blog_comment_path(@blog_comment) %> |
<%= link_to 'Back', blog_comments_path %>